export const AUDIT_LOG_ACTIONS = Object.freeze([
  { value: '', labelKey: 'reports.auditLogs.filters.allActions' },
  { value: 'player_request_created', labelKey: 'reports.auditLogs.actions.playerRequestCreated' },
  { value: 'player_approved', labelKey: 'reports.auditLogs.actions.playerApproved' },
  { value: 'player_rejected', labelKey: 'reports.auditLogs.actions.playerRejected' },
  { value: 'match_request_created', labelKey: 'reports.auditLogs.actions.matchRequestCreated' },
  { value: 'match_approved', labelKey: 'reports.auditLogs.actions.matchApproved' },
  { value: 'match_rejected', labelKey: 'reports.auditLogs.actions.matchRejected' },
  { value: 'coach_assignment_created', labelKey: 'reports.auditLogs.actions.coachAssignmentCreated' },
  { value: 'coach_assignment_updated', labelKey: 'reports.auditLogs.actions.coachAssignmentUpdated' },
  { value: 'coach_assignment_deactivated', labelKey: 'reports.auditLogs.actions.coachAssignmentDeactivated' },
  { value: 'roster_membership_added', labelKey: 'reports.auditLogs.actions.rosterMembershipAdded' },
  { value: 'roster_membership_updated', labelKey: 'reports.auditLogs.actions.rosterMembershipUpdated' },
  { value: 'roster_membership_removed', labelKey: 'reports.auditLogs.actions.rosterMembershipRemoved' },
  { value: 'player_lifecycle_changed', labelKey: 'reports.auditLogs.actions.playerLifecycleChanged' },
  { value: 'match_squad_submitted', labelKey: 'reports.auditLogs.actions.matchSquadSubmitted' },
  { value: 'match_squad_approved', labelKey: 'reports.auditLogs.actions.matchSquadApproved' },
  { value: 'match_squad_locked', labelKey: 'reports.auditLogs.actions.matchSquadLocked' },
  { value: 'match_event_created', labelKey: 'reports.auditLogs.actions.matchEventCreated' },
  { value: 'match_event_updated', labelKey: 'reports.auditLogs.actions.matchEventUpdated' },
  { value: 'match_event_deleted', labelKey: 'reports.auditLogs.actions.matchEventDeleted' },
  { value: 'match_result_updated', labelKey: 'reports.auditLogs.actions.matchResultUpdated' },
  { value: 'tournament_created', labelKey: 'reports.auditLogs.actions.tournamentCreated' },
  { value: 'tournament_updated', labelKey: 'reports.auditLogs.actions.tournamentUpdated' },
  { value: 'tournament_finalized', labelKey: 'reports.auditLogs.actions.tournamentFinalized' },
])