export const FORM_MANAGEMENT_ROUTE_NAMES = Object.freeze({
  dashboard: 'dashboard-preschool-admin-forms',
  manage: 'dashboard-preschool-admin-forms-manage',
  build: 'dashboard-preschool-admin-forms-build',
  review: 'dashboard-preschool-admin-forms-review',
  auditLog: 'dashboard-preschool-admin-lifecycle-audit',
})

export const FORM_MANAGEMENT_HERO_LINK_DEFINITIONS = Object.freeze([
  {
    key: 'build',
    icon: 'pi pi-wrench',
    titleKey: 'preschoolScaffold.formManagement.cards.newForm.title',
    titleFallback: 'Build Form',
    routeName: FORM_MANAGEMENT_ROUTE_NAMES.build,
  },
  {
    key: 'manage',
    icon: 'pi pi-folder-open',
    titleKey: 'preschoolScaffold.formManagement.cards.forms.title',
    titleFallback: 'Manage Templates',
    routeName: FORM_MANAGEMENT_ROUTE_NAMES.manage,
  },
  {
    key: 'review',
    icon: 'pi pi-chart-pie',
    titleKey: 'preschoolScaffold.formManagement.pages.review.title',
    titleFallback: 'Review Forms',
    routeName: FORM_MANAGEMENT_ROUTE_NAMES.review,
  },
])

export const FORM_MANAGEMENT_OVERVIEW_METRIC_DEFINITIONS = Object.freeze([
  {
    key: 'totalTemplates',
    icon: 'pi pi-clone',
    titleKey: 'preschoolScaffold.formManagement.pages.overview.metrics.totalTemplates.title',
    titleFallback: 'Total templates',
    descriptionKey: 'preschoolScaffold.formManagement.pages.overview.metrics.totalTemplates.description',
    descriptionFallback: 'Overview of the current template library.',
  },
  {
    key: 'drafts',
    icon: 'pi pi-pencil',
    titleKey: 'preschoolScaffold.formManagement.pages.overview.metrics.drafts.title',
    titleFallback: 'Drafts',
    descriptionKey: 'preschoolScaffold.formManagement.pages.overview.metrics.drafts.description',
    descriptionFallback: 'Templates that are still being prepared.',
  },
  {
    key: 'published',
    icon: 'pi pi-check-circle',
    titleKey: 'preschoolScaffold.formManagement.pages.overview.metrics.published.title',
    titleFallback: 'Published',
    descriptionKey: 'preschoolScaffold.formManagement.pages.overview.metrics.published.description',
    descriptionFallback: 'Templates available for active use.',
  },
  {
    key: 'pendingReview',
    icon: 'pi pi-inbox',
    titleKey: 'preschoolScaffold.formManagement.pages.overview.metrics.pendingReview.title',
    titleFallback: 'Pending review',
    descriptionKey: 'preschoolScaffold.formManagement.pages.overview.metrics.pendingReview.description',
    descriptionFallback: 'Templates waiting for approval.',
  },
  {
    key: 'archived',
    icon: 'pi pi-folder',
    titleKey: 'preschoolScaffold.formManagement.pages.overview.metrics.archived.title',
    titleFallback: 'Archived',
    descriptionKey: 'preschoolScaffold.formManagement.pages.overview.metrics.archived.description',
    descriptionFallback: 'Inactive templates kept for reference.',
  },
])

export const FORM_MANAGEMENT_QUICK_ACTION_DEFINITIONS = Object.freeze([
  {
    key: 'manage',
    icon: 'pi pi-folder-open',
    titleKey: 'preschoolScaffold.formManagement.pages.manage.title',
    titleFallback: 'Manage Templates',
    descriptionKey: 'preschoolScaffold.formManagement.pages.manage.description',
    descriptionFallback: 'Open the template catalog and related records.',
    routeName: FORM_MANAGEMENT_ROUTE_NAMES.manage,
  },
  {
    key: 'build',
    icon: 'pi pi-wrench',
    titleKey: 'preschoolScaffold.formManagement.pages.build.title',
    titleFallback: 'Build Form',
    descriptionKey: 'preschoolScaffold.formManagement.pages.build.description',
    descriptionFallback: 'Create and refine forms with the guided tools.',
    routeName: FORM_MANAGEMENT_ROUTE_NAMES.build,
  },
  {
    key: 'review',
    icon: 'pi pi-chart-pie',
    titleKey: 'preschoolScaffold.formManagement.pages.review.title',
    titleFallback: 'Review Forms',
    descriptionKey: 'preschoolScaffold.formManagement.pages.review.description',
    descriptionFallback: 'Review submission and reporting outputs.',
    routeName: FORM_MANAGEMENT_ROUTE_NAMES.review,
  },
])

export const FORM_MANAGEMENT_WORKFLOW_STEP_DEFINITIONS = Object.freeze([
  {
    key: 'createTemplate',
    icon: 'pi pi-plus-circle',
    titleKey: 'preschoolScaffold.formManagement.pages.overview.steps.createTemplate.title',
    titleFallback: 'Create template',
    descriptionKey: 'preschoolScaffold.formManagement.pages.overview.steps.createTemplate.description',
    descriptionFallback: 'Start a new preschool form template in the builder.',
  },
  {
    key: 'buildQuestions',
    icon: 'pi pi-pencil',
    titleKey: 'preschoolScaffold.formManagement.pages.overview.steps.buildQuestions.title',
    titleFallback: 'Build questions',
    descriptionKey: 'preschoolScaffold.formManagement.pages.overview.steps.buildQuestions.description',
    descriptionFallback: 'Add sections, fields, and validation rules.',
  },
  {
    key: 'publish',
    icon: 'pi pi-send',
    titleKey: 'preschoolScaffold.formManagement.pages.overview.steps.publish.title',
    titleFallback: 'Publish',
    descriptionKey: 'preschoolScaffold.formManagement.pages.overview.steps.publish.description',
    descriptionFallback: 'Make the template available to teachers and staff.',
  },
  {
    key: 'reviewSubmissions',
    icon: 'pi pi-inbox',
    titleKey: 'preschoolScaffold.formManagement.pages.overview.steps.reviewSubmissions.title',
    titleFallback: 'Review submissions',
    descriptionKey: 'preschoolScaffold.formManagement.pages.overview.steps.reviewSubmissions.description',
    descriptionFallback: 'Track responses and review outcomes.',
  },
])

export const FORM_MANAGEMENT_RESOURCE_DEFINITIONS = Object.freeze([
  {
    key: 'reports',
    icon: 'pi pi-chart-pie',
    titleKey: 'preschoolScaffold.formManagement.cards.reports.title',
    titleFallback: 'Reports',
    descriptionKey: 'preschoolScaffold.formManagement.cards.reports.description',
    descriptionFallback: 'View summary data and reports for forms.',
    routeName: FORM_MANAGEMENT_ROUTE_NAMES.reports,
  },
  {
    key: 'auditLogs',
    icon: 'pi pi-history',
    titleKey: 'preschoolScaffold.formManagement.cards.auditLogs.title',
    titleFallback: 'Audit Log',
    descriptionKey: 'preschoolScaffold.formManagement.cards.auditLogs.description',
    descriptionFallback: 'Review activity and the history of changes.',
    routeName: FORM_MANAGEMENT_ROUTE_NAMES.auditLog,
  },
])

export const FORM_MANAGEMENT_MANAGE_CARD_DEFINITIONS = Object.freeze([
  {
    key: 'dashboard',
    group: 'overview',
    icon: 'pi pi-chart-bar',
    titleKey: 'preschoolScaffold.formManagement.cards.dashboard.title',
    titleFallback: 'Forms Overview',
    descriptionKey: 'preschoolScaffold.formManagement.cards.dashboard.description',
    descriptionFallback: 'View the overview and jump into the most important areas.',
    routeName: FORM_MANAGEMENT_ROUTE_NAMES.dashboard,
  },
  {
    key: 'forms',
    group: 'manage',
    icon: 'pi pi-folder-open',
    titleKey: 'preschoolScaffold.formManagement.cards.forms.title',
    titleFallback: 'Manage Templates',
    descriptionKey: 'preschoolScaffold.formManagement.cards.forms.description',
    descriptionFallback: 'Review and organize the current template catalog.',
    routeName: FORM_MANAGEMENT_ROUTE_NAMES.manage,
  },
  {
    key: 'new-form',
    group: 'build',
    icon: 'pi pi-plus-circle',
    titleKey: 'preschoolScaffold.formManagement.cards.newForm.title',
    titleFallback: 'Build Form',
    descriptionKey: 'preschoolScaffold.formManagement.cards.newForm.description',
    descriptionFallback: 'Create a new form for a workflow or data collection flow.',
    routeName: FORM_MANAGEMENT_ROUTE_NAMES.build,
  },
  {
    key: 'submissions',
    group: 'review',
    icon: 'pi pi-inbox',
    titleKey: 'preschoolScaffold.formManagement.cards.submissions.title',
    titleFallback: 'Submissions',
    descriptionKey: 'preschoolScaffold.formManagement.cards.submissions.description',
    descriptionFallback: 'Track submissions and monitor their processing status.',
    routeName: FORM_MANAGEMENT_ROUTE_NAMES.review,
  },
  {
    key: 'wizard',
    group: 'build',
    icon: 'pi pi-sparkles',
    titleKey: 'preschoolScaffold.formManagement.cards.wizard.title',
    titleFallback: 'Wizard',
    descriptionKey: 'preschoolScaffold.formManagement.cards.wizard.description',
    descriptionFallback: 'Build forms step by step with guided assistance.',
    routeName: FORM_MANAGEMENT_ROUTE_NAMES.build,
  },
  {
    key: 'scoring',
    group: 'build',
    icon: 'pi pi-sliders-h',
    titleKey: 'preschoolScaffold.formManagement.cards.scoring.title',
    titleFallback: 'Scoring',
    descriptionKey: 'preschoolScaffold.formManagement.cards.scoring.description',
    descriptionFallback: 'Define and manage scoring rules for the active form.',
    routeName: FORM_MANAGEMENT_ROUTE_NAMES.build,
  },
  {
    key: 'print-designer',
    group: 'build',
    icon: 'pi pi-print',
    titleKey: 'preschoolScaffold.formManagement.cards.printDesigner.title',
    titleFallback: 'Print Designer',
    descriptionKey: 'preschoolScaffold.formManagement.cards.printDesigner.description',
    descriptionFallback: 'Arrange print layouts and present forms cleanly.',
    routeName: FORM_MANAGEMENT_ROUTE_NAMES.build,
  },
  {
    key: 'reports',
    group: 'review',
    icon: 'pi pi-chart-pie',
    titleKey: 'preschoolScaffold.formManagement.cards.reports.title',
    titleFallback: 'Reports',
    descriptionKey: 'preschoolScaffold.formManagement.cards.reports.description',
    descriptionFallback: 'View summary data and reports for forms.',
    routeName: FORM_MANAGEMENT_ROUTE_NAMES.reports,
  },
  {
    key: 'audit-logs',
    group: 'manage',
    icon: 'pi pi-history',
    titleKey: 'preschoolScaffold.formManagement.cards.auditLogs.title',
    titleFallback: 'Audit Log',
    descriptionKey: 'preschoolScaffold.formManagement.cards.auditLogs.description',
    descriptionFallback: 'Review activity and the history of changes.',
    routeName: FORM_MANAGEMENT_ROUTE_NAMES.auditLog,
  },
])

export function groupFormManagementActionCards(cards = FORM_MANAGEMENT_MANAGE_CARD_DEFINITIONS) {
  return {
    manage: cards.filter((card) => card.group === 'manage'),
    build: cards.filter((card) => card.group === 'build'),
    review: cards.filter((card) => card.group === 'review'),
    overview: cards.filter((card) => card.group === 'overview'),
  }
}
