export const preschoolAnalyticsDetailConfigs = {
  attendance: {
    domain: 'attendance',
    titleKey: 'preschoolAnalyticsPage.attendanceDetail',
    subtitleKey: 'preschoolAnalyticsPage.sections.attendance.subtitle',
    fetchName: 'attendance',
    backRouteName: 'dashboard-preschool-admin-analytics',
    summaryCards: [
      { labelKey: 'preschoolAnalyticsPage.attendanceRate', paths: ['summary.attendanceRate', 'summary.attendance_rate'], tone: 'emerald', interactionKey: 'attendanceRate' },
      { labelKey: 'preschoolAnalyticsPage.present', paths: ['summary.present'], tone: 'blue' },
      { labelKey: 'preschoolAnalyticsPage.absent', paths: ['summary.absent'], tone: 'rose' },
      { labelKey: 'preschoolAnalyticsPage.late', paths: ['summary.late'], tone: 'amber' },
      { labelKey: 'preschoolAnalyticsPage.excused', paths: ['summary.excused'], tone: 'slate' },
      { labelKey: 'preschoolAnalyticsPage.unexcused', paths: ['summary.unexcused'], tone: 'violet' },
    ],
    trend: {
      titleKey: 'preschoolAnalyticsPage.attendanceTrend',
      subtitleKey: 'preschoolAnalyticsPage.sections.attendance.subtitle',
      chartType: 'line',
      sources: ['charts.trend', 'trends.attendance', 'trends.thisWeek', 'datasets.topClasses'],
      emptyKey: 'preschoolAnalyticsPage.noTrendData',
    },
    breakdowns: [
      {
        titleKey: 'preschoolAnalyticsPage.byClass',
        subtitleKey: 'preschoolAnalyticsPage.sections.attendance.subtitle',
        sources: ['breakdowns.byClass'],
        emptyKey: 'preschoolAnalyticsPage.noBreakdownData',
      },
      {
        titleKey: 'preschoolAnalyticsPage.byTeacher',
        subtitleKey: 'preschoolAnalyticsPage.sections.attendance.subtitle',
        sources: ['breakdowns.byTeacher'],
        emptyKey: 'preschoolAnalyticsPage.noBreakdownData',
      },
      {
        titleKey: 'preschoolAnalyticsPage.byStudent',
        subtitleKey: 'preschoolAnalyticsPage.sections.attendance.subtitle',
        sources: ['breakdowns.byStudent'],
        emptyKey: 'preschoolAnalyticsPage.noBreakdownData',
      },
    ],
    datasets: [
      {
        sectionKey: 'topClasses',
        titleKey: 'preschoolAnalyticsPage.dataset',
        subtitleKey: 'preschoolAnalyticsPage.byClass',
        sources: ['datasets.topClasses'],
        columns: [
          { key: 'label', labelKey: 'preschoolAnalyticsPage.byClass' },
          { key: 'value', labelKey: 'preschoolAnalyticsPage.attendanceRate' },
        ],
      },
      {
        sectionKey: 'topStudents',
        titleKey: 'preschoolAnalyticsPage.dataset',
        subtitleKey: 'preschoolAnalyticsPage.byStudent',
        sources: ['datasets.topStudents'],
        columns: [
          { key: 'label', labelKey: 'preschoolAnalyticsPage.byStudent' },
          { key: 'value', labelKey: 'preschoolAnalyticsPage.attendanceRate' },
        ],
      },
    ],
  },
  sessions: {
    domain: 'sessions',
    titleKey: 'preschoolAnalyticsPage.sessionDetail',
    subtitleKey: 'preschoolAnalyticsPage.sections.sessions.subtitle',
    fetchName: 'sessions',
    backRouteName: 'dashboard-preschool-admin-analytics',
    summaryCards: [
      { labelKey: 'preschoolAnalyticsPage.sessionsGenerated', paths: ['summary.totalSessions', 'summary.sessionsGenerated', 'summary.generated'], tone: 'blue', interactionKey: 'sessionsGenerated' },
      { labelKey: 'preschoolAnalyticsPage.sessionsCompleted', paths: ['summary.completed'], tone: 'emerald', interactionKey: 'sessionsCompleted' },
      { labelKey: 'preschoolAnalyticsPage.missingSessions', paths: ['summary.missing'], tone: 'rose', interactionKey: 'missingSessions' },
      { labelKey: 'preschoolAnalyticsPage.completionRate', paths: ['summary.completionRate', 'summary.completion_rate'], tone: 'violet' },
      { labelKey: 'preschoolAnalyticsPage.attendanceRate', paths: ['summary.attendanceRate', 'summary.attendance_rate'], tone: 'amber' },
      { labelKey: 'preschoolAnalyticsPage.generatedSessions', paths: ['summary.generatedSessions', 'summary.totalSessions'], tone: 'slate' },
    ],
    trend: {
      titleKey: 'preschoolAnalyticsPage.trend',
      subtitleKey: 'preschoolAnalyticsPage.sections.sessions.subtitle',
      chartType: 'bar',
      sources: ['charts.completionTrend', 'trends.byDay', 'trends.byWeek', 'trends.byMonth'],
      emptyKey: 'preschoolAnalyticsPage.noTrendData',
    },
    breakdowns: [
      { titleKey: 'preschoolAnalyticsPage.byTeacher', subtitleKey: 'preschoolAnalyticsPage.sections.sessions.subtitle', sources: ['breakdowns.byTeacher'], emptyKey: 'preschoolAnalyticsPage.noBreakdownData' },
      { titleKey: 'preschoolAnalyticsPage.byClass', subtitleKey: 'preschoolAnalyticsPage.sections.sessions.subtitle', sources: ['breakdowns.byClass'], emptyKey: 'preschoolAnalyticsPage.noBreakdownData' },
      { titleKey: 'preschoolAnalyticsPage.byStatus', subtitleKey: 'preschoolAnalyticsPage.sections.sessions.subtitle', sources: ['breakdowns.byDay'], emptyKey: 'preschoolAnalyticsPage.noBreakdownData' },
    ],
    datasets: [
      { sectionKey: 'recentSessions', titleKey: 'preschoolAnalyticsPage.dataset', subtitleKey: 'preschoolAnalyticsPage.sessionReport', sources: ['datasets.recentSessions'], columns: [{ key: 'label', labelKey: 'preschoolAnalyticsPage.byStatus' }, { key: 'value', labelKey: 'preschoolAnalyticsPage.sessionsCompleted' }] },
      { sectionKey: 'missingSessions', titleKey: 'preschoolAnalyticsPage.dataset', subtitleKey: 'preschoolAnalyticsPage.missingSessions', sources: ['datasets.missingSessions'], columns: [{ key: 'label', labelKey: 'preschoolAnalyticsPage.byStatus' }, { key: 'value', labelKey: 'preschoolAnalyticsPage.missingSessions' }] },
    ],
  },
  alerts: {
    domain: 'alerts',
    titleKey: 'preschoolAnalyticsPage.alertDetail',
    subtitleKey: 'preschoolAnalyticsPage.sections.alerts.subtitle',
    fetchName: 'alerts',
    backRouteName: 'dashboard-preschool-admin-analytics',
    summaryCards: [
      { labelKey: 'preschoolAnalyticsPage.totalAlerts', paths: ['summary.totalAlerts', 'summary.total'], tone: 'rose' },
      { labelKey: 'preschoolAnalyticsPage.openAlerts', paths: ['summary.open', 'summary.openAlerts'], tone: 'amber' },
      { labelKey: 'preschoolAnalyticsPage.completed', paths: ['summary.completed', 'summary.completedAlerts'], tone: 'emerald' },
      { labelKey: 'preschoolAnalyticsPage.overdueAlerts', paths: ['summary.overdue', 'summary.overdueAlerts'], tone: 'violet' },
    ],
    trend: {
      titleKey: 'preschoolAnalyticsPage.trend',
      subtitleKey: 'preschoolAnalyticsPage.sections.alerts.subtitle',
      chartType: 'line',
      sources: ['trends.daily', 'trends.weekly', 'trends.monthly'],
      emptyKey: 'preschoolAnalyticsPage.noTrendData',
    },
    breakdowns: [
      { titleKey: 'preschoolAnalyticsPage.bySeverity', subtitleKey: 'preschoolAnalyticsPage.sections.alerts.subtitle', sources: ['breakdowns.bySeverity'], emptyKey: 'preschoolAnalyticsPage.noBreakdownData' },
      { titleKey: 'preschoolAnalyticsPage.byClass', subtitleKey: 'preschoolAnalyticsPage.sections.alerts.subtitle', sources: ['breakdowns.byClass'], emptyKey: 'preschoolAnalyticsPage.noBreakdownData' },
      { titleKey: 'preschoolAnalyticsPage.byTeacher', subtitleKey: 'preschoolAnalyticsPage.sections.alerts.subtitle', sources: ['breakdowns.byTeacher'], emptyKey: 'preschoolAnalyticsPage.noBreakdownData' },
      { titleKey: 'preschoolAnalyticsPage.byReason', subtitleKey: 'preschoolAnalyticsPage.sections.alerts.subtitle', sources: ['breakdowns.byAlertType'], emptyKey: 'preschoolAnalyticsPage.noBreakdownData' },
    ],
    datasets: [
      { sectionKey: 'recentAlerts', titleKey: 'preschoolAnalyticsPage.dataset', subtitleKey: 'preschoolAnalyticsPage.alertAnalytics', sources: ['datasets.recentAlerts'], columns: [{ key: 'label', labelKey: 'preschoolAnalyticsPage.bySeverity' }, { key: 'value', labelKey: 'preschoolAnalyticsPage.totalAlerts' }] },
    ],
  },
  students: {
    domain: 'students',
    titleKey: 'preschoolAnalyticsPage.studentDetail',
    subtitleKey: 'preschoolAnalyticsPage.sections.students.subtitle',
    fetchName: 'students',
    backRouteName: 'dashboard-preschool-admin-analytics',
    summaryCards: [
      { labelKey: 'preschoolAnalyticsPage.activeStudents', paths: ['summary.activeStudents'], tone: 'emerald', interactionKey: 'activeStudents' },
      { labelKey: 'preschoolAnalyticsPage.attendanceRate', paths: ['summary.attendanceRate', 'summary.attendance_rate'], tone: 'blue' },
      { labelKey: 'preschoolAnalyticsPage.alertCount', paths: ['summary.alertCount'], tone: 'rose' },
      { labelKey: 'preschoolAnalyticsPage.guardianContacts', paths: ['summary.guardianContacts'], tone: 'amber' },
      { labelKey: 'preschoolAnalyticsPage.healthAlerts', paths: ['summary.healthAlerts'], tone: 'violet' },
      { labelKey: 'preschoolAnalyticsPage.assessmentParticipation', paths: ['summary.assessmentParticipation'], tone: 'slate' },
    ],
    trend: null,
    breakdowns: [
      { titleKey: 'preschoolAnalyticsPage.byClass', subtitleKey: 'preschoolAnalyticsPage.sections.students.subtitle', sources: ['breakdowns.byClass'], emptyKey: 'preschoolAnalyticsPage.noBreakdownData' },
      { titleKey: 'preschoolAnalyticsPage.byStatus', subtitleKey: 'preschoolAnalyticsPage.sections.students.subtitle', sources: ['breakdowns.byAcademicYear'], emptyKey: 'preschoolAnalyticsPage.noBreakdownData' },
    ],
    datasets: [
      { sectionKey: 'topStudents', titleKey: 'preschoolAnalyticsPage.dataset', subtitleKey: 'preschoolAnalyticsPage.studentAnalytics', sources: ['datasets.topStudents'], columns: [{ key: 'label', labelKey: 'preschoolAnalyticsPage.byStudent' }, { key: 'value', labelKey: 'preschoolAnalyticsPage.attendanceRate' }] },
    ],
  },
  teachers: {
    domain: 'teachers',
    titleKey: 'preschoolAnalyticsPage.teacherDetail',
    subtitleKey: 'preschoolAnalyticsPage.sections.teachers.subtitle',
    fetchName: 'teachers',
    backRouteName: 'dashboard-preschool-admin-analytics',
    summaryCards: [
      { labelKey: 'preschoolAnalyticsPage.assignedClasses', paths: ['summary.assignedClasses'], tone: 'violet', interactionKey: 'assignedClasses' },
      { labelKey: 'preschoolAnalyticsPage.students', paths: ['summary.students'], tone: 'emerald' },
      { labelKey: 'preschoolAnalyticsPage.attendanceSessions', paths: ['summary.attendanceSessions'], tone: 'blue' },
      { labelKey: 'preschoolAnalyticsPage.sessionsCompleted', paths: ['summary.completedSessions'], tone: 'amber' },
      { labelKey: 'preschoolAnalyticsPage.attendanceRate', paths: ['summary.attendanceRate'], tone: 'rose', interactionKey: 'teacherUtilization' },
      { labelKey: 'preschoolAnalyticsPage.alertCount', paths: ['summary.alertCount'], tone: 'slate' },
    ],
    trend: {
      titleKey: 'preschoolAnalyticsPage.trend',
      subtitleKey: 'preschoolAnalyticsPage.sections.teachers.subtitle',
      chartType: 'bar',
      sources: ['charts.weeklyUtilization', 'charts.monthlyUtilization'],
      emptyKey: 'preschoolAnalyticsPage.noTrendData',
    },
    breakdowns: [
      { titleKey: 'preschoolAnalyticsPage.byClass', subtitleKey: 'preschoolAnalyticsPage.sections.teachers.subtitle', sources: ['breakdowns.byClass'], emptyKey: 'preschoolAnalyticsPage.noBreakdownData' },
      { titleKey: 'preschoolAnalyticsPage.byTeacher', subtitleKey: 'preschoolAnalyticsPage.sections.teachers.subtitle', sources: ['breakdowns.byTeacher'], emptyKey: 'preschoolAnalyticsPage.noBreakdownData' },
    ],
    datasets: [
      { sectionKey: 'teachers', titleKey: 'preschoolAnalyticsPage.dataset', subtitleKey: 'preschoolAnalyticsPage.teacherAnalytics', sources: ['datasets.teachers'], columns: [{ key: 'label', labelKey: 'preschoolAnalyticsPage.byTeacher' }, { key: 'value', labelKey: 'preschoolAnalyticsPage.attendanceRate' }] },
    ],
  },
  guardianContacts: {
    domain: 'guardianContacts',
    titleKey: 'preschoolAnalyticsPage.guardianContactDetail',
    subtitleKey: 'preschoolAnalyticsPage.sections.guardians.subtitle',
    fetchName: 'guardianContacts',
    backRouteName: 'dashboard-preschool-admin-analytics',
    summaryCards: [
      { labelKey: 'preschoolAnalyticsPage.contactLogs', paths: ['summary.contactLogs'], tone: 'blue', interactionKey: 'guardianContacts' },
      { labelKey: 'preschoolAnalyticsPage.followUps', paths: ['summary.followUps'], tone: 'amber' },
      { labelKey: 'preschoolAnalyticsPage.completed', paths: ['summary.completed'], tone: 'emerald' },
      { labelKey: 'preschoolAnalyticsPage.outstanding', paths: ['summary.outstanding'], tone: 'rose' },
    ],
    trend: {
      titleKey: 'preschoolAnalyticsPage.trend',
      subtitleKey: 'preschoolAnalyticsPage.sections.guardians.subtitle',
      chartType: 'bar',
      sources: ['trends.daily', 'trends.weekly', 'trends.monthly'],
      emptyKey: 'preschoolAnalyticsPage.noTrendData',
    },
    breakdowns: [
      { titleKey: 'preschoolAnalyticsPage.byMethod', subtitleKey: 'preschoolAnalyticsPage.sections.guardians.subtitle', sources: ['breakdowns.byMethod'], emptyKey: 'preschoolAnalyticsPage.noBreakdownData' },
      { titleKey: 'preschoolAnalyticsPage.byReason', subtitleKey: 'preschoolAnalyticsPage.sections.guardians.subtitle', sources: ['breakdowns.byReason'], emptyKey: 'preschoolAnalyticsPage.noBreakdownData' },
      { titleKey: 'preschoolAnalyticsPage.byTeacher', subtitleKey: 'preschoolAnalyticsPage.sections.guardians.subtitle', sources: ['breakdowns.byStaffMember'], emptyKey: 'preschoolAnalyticsPage.noBreakdownData' },
      { titleKey: 'preschoolAnalyticsPage.byClass', subtitleKey: 'preschoolAnalyticsPage.sections.guardians.subtitle', sources: ['breakdowns.byClass'], emptyKey: 'preschoolAnalyticsPage.noBreakdownData' },
    ],
    datasets: [
      { sectionKey: 'recentCommunications', titleKey: 'preschoolAnalyticsPage.dataset', subtitleKey: 'preschoolAnalyticsPage.guardianAnalytics', sources: ['datasets.recentCommunications'], columns: [{ key: 'label', labelKey: 'preschoolAnalyticsPage.byMethod' }, { key: 'value', labelKey: 'preschoolAnalyticsPage.contactLogs' }] },
    ],
  },
}
